<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Start منتجات فئة 1,2: Fresh Meat (Beef, Chicken)
            [
                'category_id' => 1,
                'name' => 'Beef Steak',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-steak.jpg',
                'summary' => 'Juicy beef steak, perfect for grilling.',
                'description' => 'Tender and flavorful steak, great for any occasion.',
                'quantity' => 50,
                'unit' => 'kg',
                'tags' => ['beef', 'steak', 'protein'],
                'price' => 120.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Ground Beef',
                'picture' => 'assets/website/img/products/fresh-meat/meat/ground-beef.jpg',
                'summary' => 'Fresh ground beef for various dishes.',
                'description' => 'Versatile ground beef, ideal for burgers and tacos.',
                'quantity' => 30,
                'unit' => 'kg',
                'tags' => ['beef', 'ground', 'protein'],
                'price' => 90.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Beef Ribs',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-ribs.jpg',
                'summary' => 'Tender beef ribs for barbecue.',
                'description' => 'Delicious beef ribs, perfect for slow cooking.',
                'quantity' => 20,
                'unit' => 'kg',
                'tags' => ['beef', 'ribs', 'bbq'],
                'price' => 150.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Beef Jerky',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-jerky.jpg',
                'summary' => 'Savory beef jerky for snacking.',
                'description' => 'High-protein snack, great for on-the-go.',
                'quantity' => 100,
                'unit' => 'kg',
                'tags' => ['snacks', 'beef', 'protein'],
                'price' => 250.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Beef Tenderloin',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-tenderloin.jpg',
                'summary' => 'Premium beef tenderloin cut.',
                'description' => 'Top-quality tenderloin, perfect for fine dining.',
                'quantity' => 15,
                'unit' => 'kg',
                'tags' => ['beef', 'tenderloin', 'premium'],
                'price' => 200.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Beef Shank',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-shank.jpg',
                'summary' => 'Flavorful beef shank for soups and stews.',
                'description' => 'Ideal for slow-cooking, adds rich flavor to dishes.',
                'quantity' => 40,
                'unit' => 'kg',
                'tags' => ['beef', 'shank', 'soup'],
                'price' => 80.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Beef Brisket',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-brisket.jpg',
                'summary' => 'Juicy beef brisket, perfect for smoking.',
                'description' => 'Rich and tender brisket, ideal for BBQ enthusiasts.',
                'quantity' => 25,
                'unit' => 'kg',
                'tags' => ['beef', 'brisket', 'bbq'],
                'price' => 180.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Beef Tongue',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-tongue.jpg',
                'summary' => 'Tender beef tongue, great for tacos and sandwiches.',
                'description' => 'Flavorful and rich, perfect for traditional dishes.',
                'quantity' => 10,
                'unit' => 'kg',
                'tags' => ['beef', 'tongue', 'tacos'],
                'price' => 220.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Beef Liver',
                'picture' => 'assets/website/img/products/fresh-meat/meat/beef-liver.jpg',
                'summary' => 'Nutritious beef liver, high in vitamins.',
                'description' => 'Rich in iron and essential nutrients, great for health.',
                'quantity' => 15,
                'unit' => 'kg',
                'tags' => ['beef', 'liver', 'nutritious'],
                'price' => 70.00,
            ],
            [
                'category_id' => 1,
                'name' => 'Lamb Chops',
                'picture' => 'assets/website/img/products/fresh-meat/meat/lamb-chops.jpg',
                'summary' => 'Juicy lamb chops.',
                'description' => 'Tender and flavorful lamb chops, perfect for grilling or roasting.',
                'quantity' => 50,
                'unit' => 'kg',
                'tags' => ['meat', 'lamb', 'chops'],
                'price' => 12.00,
            ],
            // منتجات فئة 2: Chicken
            [
                'category_id' => 2,
                'name' => 'Grilled Chicken Breast',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/grilled-chicken-breast.jpg',
                'summary' => 'Lean grilled chicken breast, healthy and delicious.',
                'description' => 'Perfect for salads and healthy meals.',
                'quantity' => 40,
                'unit' => 'kg',
                'tags' => ['chicken', 'grilled', 'healthy'],
                'price' => 80.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Chicken Wings',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/chicken-wings.jpg',
                'summary' => 'Crispy chicken wings for snacking.',
                'description' => 'Spicy and crispy wings, perfect for parties.',
                'quantity' => 60,
                'unit' => 'kg',
                'tags' => ['chicken', 'wings', 'snacks'],
                'price' => 70.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Whole Chicken',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/whole-chicken.jpg',
                'summary' => 'Fresh whole chicken for roasting.',
                'description' => 'Perfectly fresh whole chicken for family dinners.',
                'quantity' => 30,
                'unit' => 'piece',
                'tags' => ['chicken', 'whole', 'roast'],
                'price' => 120.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Chicken Thighs',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/chicken-thighs.jpg',
                'summary' => 'Juicy chicken thighs for grilling.',
                'description' => 'Flavorful thighs, ideal for barbecues.',
                'quantity' => 25,
                'unit' => 'kg',
                'tags' => ['chicken', 'thighs', 'grilling'],
                'price' => 85.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Chicken Sausages',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/chicken-sausages.jpg',
                'summary' => 'Tasty chicken sausages for breakfast.',
                'description' => 'Delicious chicken sausages, great for brunch.',
                'quantity' => 50,
                'unit' => 'kg',
                'tags' => ['chicken', 'sausages', 'breakfast'],
                'price' => 95.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Chicken Drumsticks',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/chicken-drumsticks.jpg',
                'summary' => 'Savory chicken drumsticks, great for grilling.',
                'description' => 'Tender and juicy drumsticks, perfect for any meal.',
                'quantity' => 45,
                'unit' => 'kg',
                'tags' => ['chicken', 'drumsticks', 'grilling'],
                'price' => 75.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Chicken Breast Fillets',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/chicken-breast-fillets.jpg',
                'summary' => 'Boneless chicken breast fillets, easy to cook.',
                'description' => 'Quick and easy chicken fillets for a healthy meal.',
                'quantity' => 50,
                'unit' => 'kg',
                'tags' => ['chicken', 'breast', 'fillets'],
                'price' => 90.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Chicken Cutlets',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/chicken-cutlets.jpg',
                'summary' => 'Tender chicken cutlets, perfect for frying.',
                'description' => 'Crispy and golden cutlets, ideal for family meals.',
                'quantity' => 35,
                'unit' => 'kg',
                'tags' => ['chicken', 'cutlets', 'fried'],
                'price' => 85.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Marinated Chicken Skewers',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/marinated-chicken-skewers.jpg',
                'summary' => 'Flavorful marinated chicken skewers, ready to grill.',
                'description' => 'Perfect for barbecues, just grill and serve.',
                'quantity' => 20,
                'unit' => 'kg',
                'tags' => ['chicken', 'skewers', 'marinated'],
                'price' => 95.00,
            ],
            [
                'category_id' => 2,
                'name' => 'Turkey',
                'picture' => 'assets/website/img/products/fresh-meat/chicken/turkey.jpg',
                'summary' => 'Lean turkey meat for various dishes.',
                'description' => 'Great for sandwiches or roasting.',
                'quantity' => 50,
                'unit' => 'kg',
                'tags' => ['chicken', 'turkey', 'lean'],
                'price' => 95.00,
            ],
        // End منتجات فئة 1,2 Fresh Meat (Beef, Chicken) 

        // Start منتجات فئة 3,4: Vegetables (Leafy Greens, Root Vegetables)
        // منتجات فئة 3: Leafy Greens
        [
            'category_id' => 3,
            'name' => 'Arugula',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/arugula.jpg',
            'summary' => 'Fresh arugula.',
            'description' => 'Peppery flavor, great for salads and garnishes.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['leafy greens', 'arugula', 'fresh'],
            'price' => 3.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Kale',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/kale.jpg',
            'summary' => 'Fresh kale.',
            'description' => 'Nutritious and versatile, perfect for salads and smoothies.',
            'quantity' => 70,
            'unit' => 'kg',
            'tags' => ['leafy greens', 'kale', 'fresh'],
            'price' => 2.50,
        ],
        [
            'category_id' => 3,
            'name' => 'Spinach',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/spinach.jpg',
            'summary' => 'Fresh spinach.',
            'description' => 'Rich in iron, great for cooking and salads.',
            'quantity' => 80,
            'unit' => 'kg',
            'tags' => ['leafy greens', 'spinach', 'fresh'],
            'price' => 2.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Swiss Chard',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/swiss-chard.jpg',
            'summary' => 'Fresh Swiss chard.',
            'description' => 'Mild and slightly sweet, perfect for sautéing.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['leafy greens', 'swiss chard', 'fresh'],
            'price' => 2.80,
        ],
        [
            'category_id' => 3,
            'name' => 'Spinach',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/spinach.jpg',
            'summary' => 'Fresh spinach for salads and smoothies.',
            'description' => 'Nutritious spinach, rich in vitamins.',
            'quantity' => 100,
            'unit' => 'kg',
            'tags' => ['leafy', 'greens', 'healthy'],
            'price' => 30.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Kale',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/kale.jpg',
            'summary' => 'Superfood kale for healthy dishes.',
            'description' => 'Organic kale, perfect for salads and juices.',
            'quantity' => 80,
            'unit' => 'kg',
            'tags' => ['leafy', 'kale', 'superfood'],
            'price' => 40.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Romaine Lettuce',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/romaine-lettuce.jpg',
            'summary' => 'Crisp romaine lettuce for salads.',
            'description' => 'Fresh romaine, ideal for Caesar salads.',
            'quantity' => 120,
            'unit' => 'kg',
            'tags' => ['leafy', 'lettuce', 'fresh'],
            'price' => 25.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Swiss Chard',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/swiss-chard.jpg',
            'summary' => 'Colorful Swiss chard for sautéing.',
            'description' => 'Nutritious Swiss chard, great for cooking.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['leafy', 'chard', 'healthy'],
            'price' => 45.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Mustard Greens',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/mustard-greens.jpg',
            'summary' => 'Spicy mustard greens for salads and cooking.',
            'description' => 'Vibrant mustard greens with a peppery taste.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['leafy', 'mustard', 'greens'],
            'price' => 38.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Collard Greens',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/collard-greens.jpg',
            'summary' => 'Hearty collard greens for steaming and sautéing.',
            'description' => 'Rich in nutrients, perfect for Southern dishes.',
            'quantity' => 70,
            'unit' => 'kg',
            'tags' => ['leafy', 'collard', 'greens'],
            'price' => 42.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Broccoli',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/broccoli.jpg',
            'summary' => 'Fresh broccoli.',
            'description' => 'Rich in vitamins and great for steaming.',
            'quantity' => 100,
            'unit' => 'kg',
            'tags' => ['leafy greens', 'broccoli', 'fresh'],
            'price' => 2.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Romaine Lettuce',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/romaine-lettuce.jpg',
            'summary' => 'Crisp romaine lettuce.',
            'description' => 'Perfect for salads and wraps.',
            'quantity' => 80,
            'unit' => 'kg',
            'tags' => ['leafy greens', 'romaine', 'fresh'],
            'price' => 1.50,
        ],
        [
            'category_id' => 3,
            'name' => 'Bok Choy',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/bok-choy.jpg',
            'summary' => 'Crisp bok choy for stir-frying.',
            'description' => 'Fresh bok choy, ideal for Asian recipes.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['leafy', 'bok choy', 'stir-fry'],
            'price' => 30.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Cabbage',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/cabbage.jpg',
            'summary' => 'Fresh cabbage for salads and cooking.',
            'description' => 'Versatile cabbage, great for coleslaw and stir-fries.',
            'quantity' => 90,
            'unit' => 'kg',
            'tags' => ['leafy', 'cabbage', 'fresh'],
            'price' => 20.00,
        ],
        [
            'category_id' => 3,
            'name' => 'Watercress',
            'picture' => 'assets/website/img/products/vegetables/leafy-greens/watercress.jpg',
            'summary' => 'Peppery watercress for salads and garnishes.',
            'description' => 'Nutritious watercress, perfect for adding flavor.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['leafy', 'watercress', 'healthy'],
            'price' => 50.00,
        ],

        // منتجات فئة 4: Root Vegetables
        [
            'category_id' => 4,
            'name' => 'Carrots',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/carrots.jpg',
            'summary' => 'Crunchy carrots, perfect for snacking.',
            'description' => 'Fresh carrots, great for salads and stews.',
            'quantity' => 150,
            'unit' => 'kg',
            'tags' => ['vegetables', 'carrots', 'fresh'],
            'price' => 1.50, 
        ], 
        [
            'category_id' => 4,
            'name' => 'Cucumbers',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/cucumbers.jpg',
            'summary' => 'Fresh cucumbers.',
            'description' => 'Crisp and refreshing, ideal for salads.',
            'quantity' => 120,
            'unit' => 'kg',
            'tags' => ['root vegetables', 'cucumbers', 'fresh'],
            'price' => 1.00,
        ],
        [
            'category_id' => 4,
            'name' => 'Tomatoes',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/tomatoes.jpg',
            'summary' => 'Fresh tomatoes.',
            'description' => 'Juicy and ripe, ideal for salads and sauces.',
            'quantity' => 90,
            'unit' => 'kg',
            'tags' => ['root vegetables', 'tomatoes', 'fresh'],
            'price' => 1.20,
        ],
        [
            'category_id' => 4,
            'name' => 'Potatoes',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/potatoes.jpg',
            'summary' => 'Versatile potatoes for various dishes.',
            'description' => 'Fresh potatoes, perfect for mashing or frying.',
            'quantity' => 200,
            'unit' => 'kg',
            'tags' => ['vegetables', 'potatoes', 'fresh'],
            'price' => 1.20, 
        ],
        [
            'category_id' => 4,
            'name' => 'Beets',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/beets.jpg',
            'summary' => 'Sweet beets for salads and roasting.',
            'description' => 'Nutritious beets, great for salads and sides.',
            'quantity' => 70,
            'unit' => 'kg',
            'tags' => ['vegetables', 'beets', 'healthy'],
            'price' => 2.00, 
        ],
        [
            'category_id' => 4,
            'name' => 'Sweet Potatoes',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/sweet-potatoes.jpg',
            'summary' => 'Healthy sweet potatoes for baking.',
            'description' => 'Delicious sweet potatoes, great for roasting.',
            'quantity' => 80,
            'unit' => 'kg',
            'tags' => ['vegetables', 'sweet potatoes', 'healthy'],
            'price' => 1.80, 
        ],
        [
            'category_id' => 4,
            'name' => 'Turnips',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/turnips.jpg',
            'summary' => 'Hearty turnips for soups and stews.',
            'description' => 'Nutritious turnips, perfect for cooking.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['vegetables', 'turnips', 'fresh'],
            'price' => 1.30, 
        ],
        [
            'category_id' => 4,
            'name' => 'Radishes',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/radishes.jpg',
            'summary' => 'Crisp radishes for salads and snacks.',
            'description' => 'Fresh radishes, adding a crunchy bite to dishes.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['vegetables', 'radishes', 'fresh'],
            'price' => 1.00, 
        ],
        [
            'category_id' => 4,
            'name' => 'Parsnips',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/parsnips.jpg',
            'summary' => 'Sweet parsnips for roasting and mashing.',
            'description' => 'Nutritious parsnips, a great alternative to potatoes.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['vegetables', 'parsnips', 'healthy'],
            'price' => 2.50, 
        ],
        [
            'category_id' => 4,
            'name' => 'Yams',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/yams.jpg',
            'summary' => 'Delicious yams for baking and cooking.',
            'description' => 'Nutritious yams, great for various dishes.',
            'quantity' => 90,
            'unit' => 'kg',
            'tags' => ['vegetables', 'yams', 'healthy'],
            'price' => 2.20, 
        ],
        [
            'category_id' => 4,
            'name' => 'Celeriac',
            'picture' => 'assets/website/img/products/vegetables/root-vegetables/celeriac.jpg',
            'summary' => 'Unique celeriac for soups and purees.',
            'description' => 'Nutritious celeriac, adding a distinct flavor to meals.',
            'quantity' => 30,
            'unit' => 'kg',
            'tags' => ['vegetables', 'celeriac', 'fresh'],
            'price' => 3.00, 
        ],
        // End منتجات فئة 3,4: Vegetables (Leafy Greens, Root Vegetables)

        // Start منتجات فئة 5,6: Fruit & Nut Gifts (Mixed Nuts, Dried Fruits)
        // منتجات فئة 5: Mixed Nuts
        // Mixed Nuts (Category 5)
        [
            'category_id' => 5,
            'name' => 'Almonds',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/almonds.jpg',
            'summary' => 'Crunchy almonds, perfect for snacking.',
            'description' => 'Raw almonds, a great source of healthy fats and proteins.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['nuts', 'almonds', 'healthy'],
            'price' => 150.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Cashews',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/cashews.jpg',
            'summary' => 'Creamy cashews for snacks and cooking.',
            'description' => 'Roasted cashews, rich in flavor and nutrients.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['nuts', 'cashews', 'snacks'],
            'price' => 180.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Walnuts',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/walnuts.jpg',
            'summary' => 'Nutty walnuts for baking and salads.',
            'description' => 'Chopped walnuts, great for adding crunch to dishes.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['nuts', 'walnuts', 'baking'],
            'price' => 200.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Pistachios',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/pistachios.jpg',
            'summary' => 'Delicious pistachios for snacking.',
            'description' => 'Salted pistachios, perfect for any occasion.',
            'quantity' => 30,
            'unit' => 'kg',
            'tags' => ['nuts', 'pistachios', 'snacks'],
            'price' => 220.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Mixed Nuts',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/mixed-nuts.jpg',
            'summary' => 'A blend of assorted nuts for healthy snacking.',
            'description' => 'A delicious mix of almonds, cashews, walnuts, and pistachios.',
            'quantity' => 70,
            'unit' => 'kg',
            'tags' => ['nuts', 'mixed nuts', 'healthy'],
            'price' => 250.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Brazil Nuts',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/brazil-nuts.jpg',
            'summary' => 'Rich Brazil nuts for healthy snacking.',
            'description' => 'These nuts are rich in selenium and perfect for boosting energy.',
            'quantity' => 25,
            'unit' => 'kg',
            'tags' => ['nuts', 'brazil nuts', 'healthy'],
            'price' => 300.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Hazelnuts',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/hazelnuts.jpg',
            'summary' => 'Nutty hazelnuts for baking and snacking.',
            'description' => 'Roasted hazelnuts, ideal for desserts and snacks.',
            'quantity' => 45,
            'unit' => 'kg',
            'tags' => ['nuts', 'hazelnuts', 'baking'],
            'price' => 250.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Macadamia Nuts',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/macadamia-nuts.jpg',
            'summary' => 'Rich and buttery macadamia nuts.',
            'description' => 'These nuts are perfect for cookies and desserts.',
            'quantity' => 20,
            'unit' => 'kg',
            'tags' => ['nuts', 'macadamia', 'desserts'],
            'price' => 400.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Pecans',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/pecans.jpg',
            'summary' => 'Sweet pecans for cooking and snacking.',
            'description' => 'These nuts are ideal for pies and salads.',
            'quantity' => 35,
            'unit' => 'kg',
            'tags' => ['nuts', 'pecans', 'cooking'],
            'price' => 220.00,
        ],
        [
            'category_id' => 5,
            'name' => 'Roasted Mixed Nuts',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/mixed-nuts/roasted-mixed-nuts.jpg',
            'summary' => 'A crunchy mix of roasted nuts.',
            'description' => 'A savory blend of roasted almonds, cashews, and peanuts.',
            'quantity' => 55,
            'unit' => 'kg',
            'tags' => ['nuts', 'roasted', 'snacks'],
            'price' => 280.00,
        ],

        // منتجات فئة 6: Dried Fruits
        // Dried Fruits (Category 6)
        [
            'category_id' => 6,
            'name' => 'Dried Apricots',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-apricots.jpg',
            'summary' => 'Sweet and chewy dried apricots.',
            'description' => 'Nutritious dried apricots, perfect for snacking or baking.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'apricots', 'snacks'],
            'price' => 6.00,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Figs',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-figs.jpg',
            'summary' => 'Nutty dried figs for healthy snacking.',
            'description' => 'Sweet dried figs, high in fiber and antioxidants.',
            'quantity' => 30,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'figs', 'healthy'],
            'price' => 8.00,
        ],
        [
            'category_id' => 6,
            'name' => 'Raisins',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/raisins.jpg',
            'summary' => 'Sweet raisins for baking and snacking.',
            'description' => 'Natural raisins, perfect for adding to cereals and desserts.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'raisins', 'baking'],
            'price' => 4.00,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Mango',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-mango.jpg',
            'summary' => 'Tropical dried mango slices.',
            'description' => 'Sweet and tangy dried mango, ideal for snacks.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'mango', 'snacks'],
            'price' => 7.50,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Pineapple',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-pineapple.jpg',
            'summary' => 'Tasty dried pineapple for snacks and desserts.',
            'description' => 'Deliciously sweet dried pineapple rings.',
            'quantity' => 35,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'pineapple', 'snacks'],
            'price' => 9.00,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Cranberries',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-cranberries.jpg',
            'summary' => 'Tart dried cranberries for salads and snacks.',
            'description' => 'Sweetened dried cranberries, perfect for salads and baking.',
            'quantity' => 45,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'cranberries', 'healthy'],
            'price' => 5.50,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Cherries',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-cherries.jpg',
            'summary' => 'Tangy dried cherries for snacking or baking.',
            'description' => 'Perfect for adding a touch of sweetness to your desserts.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'cherries', 'snacks'],
            'price' => 12.00,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Dates',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-dates.jpg',
            'summary' => 'Sweet and nutritious dried dates.',
            'description' => 'Naturally sweet dates, high in energy and fiber.',
            'quantity' => 70,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'dates', 'snacks'],
            'price' => 6.50,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Peaches',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-peaches.jpg',
            'summary' => 'Chewy dried peaches for healthy snacking.',
            'description' => 'Sweet and nutritious dried peaches.',
            'quantity' => 25,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'peaches', 'healthy'],
            'price' => 11.00,
        ],
        [
            'category_id' => 6,
            'name' => 'Dried Coconut',
            'picture' => 'assets/website/img/products/fruit-nut-gifts/dried-fruits/dried-coconut.jpg',
            'summary' => 'Delicious dried coconut slices.',
            'description' => 'Tropical dried coconut for snacking or adding to desserts.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['dried fruits', 'coconut', 'snacks'],
            'price' => 5.00,
        ],
        // End منتجات فئة 5,6: Fruit & Nut Gifts (Mixed Nuts, Dried Fruits)
        // Start منتجات فئة 7,8: Fresh Berries (Strawberries, Blueberries)
        // Strawberries (Category 7)
        [
            'category_id' => 7,
            'name' => 'Fresh Organic Strawberries',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/organic-strawberries.jpg',
            'summary' => 'Sweet and juicy organic strawberries.',
            'description' => 'Freshly picked organic strawberries, perfect for healthy snacking.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['strawberries', 'organic', 'fresh'],
            'price' => 35.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Frozen Strawberries',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/frozen-strawberries.jpg',
            'summary' => 'Frozen strawberries for smoothies and desserts.',
            'description' => 'Perfectly frozen strawberries, ideal for baking and blending.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['strawberries', 'frozen', 'smoothies'],
            'price' => 25.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Chocolate-Covered Strawberries',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/chocolate-strawberries.jpg',
            'summary' => 'Delicious strawberries dipped in chocolate.',
            'description' => 'Perfect for gifting or indulgence, these chocolate-covered strawberries are a treat.',
            'quantity' => 30,
            'unit' => 'piece',
            'tags' => ['strawberries', 'chocolate', 'gifts'],
            'price' => 45.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Strawberry Jam',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/strawberry-jam.jpg',
            'summary' => 'Homemade strawberry jam.',
            'description' => 'Sweet and tangy strawberry jam, perfect for spreading on toast or adding to desserts.',
            'quantity' => 60,
            'unit' => 'piece',
            'tags' => ['strawberries', 'jam', 'homemade'],
            'price' => 20.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Strawberry Smoothie Pack',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/strawberry-smoothie-pack.jpg',
            'summary' => 'Pre-packed strawberries for smoothies.',
            'description' => 'Conveniently packed strawberries ready for blending into your favorite smoothie.',
            'quantity' => 45,
            'unit' => 'piece',
            'tags' => ['strawberries', 'smoothies', 'pack'],
            'price' => 30.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Freshly Picked Strawberries',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/fresh-strawberries.jpg',
            'summary' => 'Fresh strawberries picked daily.',
            'description' => 'Fresh strawberries with a sweet and juicy taste, perfect for snacking or adding to desserts.',
            'quantity' => 70,
            'unit' => 'kg',
            'tags' => ['strawberries', 'fresh', 'healthy'],
            'price' => 40.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Strawberry Yogurt',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/strawberry-yogurt.jpg',
            'summary' => 'Creamy strawberry yogurt.',
            'description' => 'Delicious yogurt mixed with fresh strawberry pieces.',
            'quantity' => 35,
            'unit' => 'kg',
            'tags' => ['strawberries', 'yogurt', 'dairy'],
            'price' => 15.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Strawberry Tarts',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/strawberry-tarts.jpg',
            'summary' => 'Homemade strawberry tarts.',
            'description' => 'Perfectly baked tarts filled with fresh strawberry jam and cream.',
            'quantity' => 40,
            'unit' => 'piece',
            'tags' => ['strawberries', 'tarts', 'desserts'],
            'price' => 50.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Dried Strawberries',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/dried-strawberries.jpg',
            'summary' => 'Delicious dried strawberries for snacks.',
            'description' => 'Sweet and chewy dried strawberries, perfect for healthy snacking or adding to cereals.',
            'quantity' => 25,
            'unit' => 'piece',
            'tags' => ['strawberries', 'dried', 'snacks'],
            'price' => 35.00,
        ],
        [
            'category_id' => 7,
            'name' => 'Strawberry Salad',
            'picture' => 'assets/website/img/products/fresh-berries/blueberries/strawberry-salad.jpg',
            'summary' => 'Fresh strawberry salad mix.',
            'description' => 'A healthy blend of fresh strawberries, greens, and nuts.',
            'quantity' => 20,
            'unit' => 'piece',
            'tags' => ['strawberries', 'salad', 'healthy'],
            'price' => 28.00,
        ],
        // Blueberries (Category 8)
        [
            'category_id' => 8,
            'name' => 'Fresh Organic Blueberries',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/organic-blueberries.jpg',
            'summary' => 'Juicy and sweet organic blueberries.',
            'description' => 'Fresh organic blueberries, great for snacking or adding to cereals.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['blueberries', 'organic', 'fresh'],
            'price' => 40.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Frozen Blueberries',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/frozen-blueberries.jpg',
            'summary' => 'Frozen blueberries for smoothies and baking.',
            'description' => 'Perfectly frozen blueberries, great for blending or adding to pies.',
            'quantity' => 45,
            'unit' => 'kg',
            'tags' => ['blueberries', 'frozen', 'smoothies'],
            'price' => 30.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Blueberry Muffins',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/blueberry-muffins.jpg',
            'summary' => 'Freshly baked blueberry muffins.',
            'description' => 'Moist and fluffy blueberry muffins, perfect for breakfast or snacks.',
            'quantity' => 35,
            'unit' => 'piece',
            'tags' => ['blueberries', 'muffins', 'baking'],
            'price' => 50.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Blueberry Jam',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/blueberry-jam.jpg',
            'summary' => 'Sweet homemade blueberry jam.',
            'description' => 'Fresh blueberry jam, ideal for spreading on toast or using in desserts.',
            'quantity' => 60,
            'unit' => 'piece',
            'tags' => ['blueberries', 'jam', 'homemade'],
            'price' => 25.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Blueberry Smoothie Pack',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/blueberry-smoothie-pack.jpg',
            'summary' => 'Pre-packed blueberries for smoothies.',
            'description' => 'Fresh blueberries conveniently packed for making smoothies.',
            'quantity' => 40,
            'unit' => 'piece',
            'tags' => ['blueberries', 'smoothies', 'pack'],
            'price' => 35.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Dried Blueberries',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/dried-blueberries.jpg',
            'summary' => 'Sweet and chewy dried blueberries.',
            'description' => 'Great for adding to cereals, salads, or enjoying as a snack.',
            'quantity' => 50,
            'unit' => 'piece',
            'tags' => ['blueberries', 'dried', 'snacks'],
            'price' => 30.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Blueberry Pancake Mix',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/blueberry-pancake-mix.jpg',
            'summary' => 'Delicious blueberry pancake mix.',
            'description' => 'Fluffy blueberry pancakes made easy with this mix.',
            'quantity' => 30,
            'unit' => 'piece',
            'tags' => ['blueberries', 'pancakes', 'baking'],
            'price' => 40.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Blueberry Yogurt',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/blueberry-yogurt.jpg',
            'summary' => 'Creamy blueberry yogurt.',
            'description' => 'Fresh and creamy yogurt with blueberry pieces mixed in.',
            'quantity' => 45,
            'unit' => 'kg',
            'tags' => ['blueberries', 'yogurt', 'dairy'],
            'price' => 20.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Blueberry Tart',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/blueberry-tart.jpg',
            'summary' => 'Freshly baked blueberry tart.',
            'description' => 'A delicious blueberry tart, perfect for dessert.',
            'quantity' => 25,
            'unit' => 'piece',
            'tags' => ['blueberries', 'tart', 'baking'],
            'price' => 55.00,
        ],
        [
            'category_id' => 8,
            'name' => 'Blueberry Salad',
            'picture' => 'assets/website/img/products/fresh-berries/strawberries/blueberry-salad.jpg',
            'summary' => 'Fresh blueberry salad with greens.',
            'description' => 'A healthy mix of blueberries, greens, and nuts for a refreshing salad.',
            'quantity' => 20,
            'unit' => 'piece',
            'tags' => ['blueberries', 'salad', 'healthy'],
            'price' => 30.00,
        ],
        // End منتجات فئة 7,8: Fresh Berries (Strawberries, Blueberries)

        // Start منتجات فئة 9,10: Ocean Foods (Fresh Fish, Shrimp Prawns)
        // Fresh Fish (Category 9)
        [
            'category_id' => 9,
            'name' => 'Fresh Salmon',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-salmon.jpg',
            'summary' => 'Freshly caught Atlantic salmon.',
            'description' => 'Rich in omega-3 fatty acids, this fresh salmon is perfect for grilling or baking.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['salmon', 'fresh', 'seafood'],
            'price' => 80.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Tuna Steaks',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/tuna-steaks.jpg',
            'summary' => 'Thick tuna steaks, freshly caught.',
            'description' => 'Ideal for grilling or searing, these fresh tuna steaks are packed with flavor.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['tuna', 'steaks', 'fresh'],
            'price' => 90.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Fresh Cod',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-cod.jpg',
            'summary' => 'Mild and flaky fresh cod fillets.',
            'description' => 'Perfect for frying, grilling, or baking, these fresh cod fillets are a seafood lover’s delight.',
            'quantity' => 45,
            'unit' => 'kg',
            'tags' => ['cod', 'fresh', 'seafood'],
            'price' => 60.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Whole Fresh Mackerel',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/whole-mackerel.jpg',
            'summary' => 'Whole mackerel freshly caught.',
            'description' => 'Fresh mackerel, rich in omega-3, ready for grilling or smoking.',
            'quantity' => 55,
            'unit' => 'kg',
            'tags' => ['mackerel', 'whole', 'seafood'],
            'price' => 45.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Fresh Halibut',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-halibut.jpg',
            'summary' => 'Thick and meaty fresh halibut fillets.',
            'description' => 'These fresh halibut fillets are ideal for pan-searing or baking.',
            'quantity' => 35,
            'unit' => 'kg',
            'tags' => ['halibut', 'fillets', 'seafood'],
            'price' => 110.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Fresh Trout',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-trout.jpg',
            'summary' => 'Whole trout freshly caught from clean waters.',
            'description' => 'Perfect for grilling, these fresh trout offer a rich and delicate flavor.',
            'quantity' => 25,
            'unit' => 'kg',
            'tags' => ['trout', 'whole', 'fresh'],
            'price' => 55.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Fresh Sea Bass',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-sea-bass.jpg',
            'summary' => 'Fresh whole sea bass.',
            'description' => 'Delicate and flavorful, this fresh sea bass is perfect for grilling or baking.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['sea bass', 'whole', 'seafood'],
            'price' => 75.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Fresh Swordfish',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-swordfish.jpg',
            'summary' => 'Fresh swordfish steaks.',
            'description' => 'Thick and hearty swordfish steaks, great for grilling or pan-searing.',
            'quantity' => 20,
            'unit' => 'kg',
            'tags' => ['swordfish', 'steaks', 'seafood'],
            'price' => 120.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Fresh Sardines',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-sardines.jpg',
            'summary' => 'Whole fresh sardines, ready to cook.',
            'description' => 'Perfect for grilling or frying, these fresh sardines are a flavorful and healthy option.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['sardines', 'whole', 'seafood'],
            'price' => 30.00,
        ],
        [
            'category_id' => 9,
            'name' => 'Fresh Snapper',
            'picture' => 'assets/website/img/products/ocean-foods/fresh-fish/fresh-snapper.jpg',
            'summary' => 'Whole fresh snapper, rich in flavor.',
            'description' => 'This whole fresh snapper is perfect for grilling, baking, or frying.',
            'quantity' => 50,
            'unit' => 'kg',
            'tags' => ['snapper', 'whole', 'seafood'],
            'price' => 85.00,
        ],
        // Shrimp & Prawns (Category 10)
        [
            'category_id' => 10,
            'name' => 'Jumbo Shrimp',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/jumbo-shrimp.jpg',
            'summary' => 'Jumbo-sized shrimp, fresh and delicious.',
            'description' => 'Perfect for grilling, sautéing, or adding to pasta dishes, these jumbo shrimp are a seafood favorite.',
            'quantity' => 30,
            'unit' => 'kg',
            'tags' => ['shrimp', 'jumbo', 'seafood'],
            'price' => 120.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Fresh Prawns',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/fresh-prawns.jpg',
            'summary' => 'Freshly caught prawns.',
            'description' => 'These prawns are fresh, juicy, and perfect for a variety of dishes.',
            'quantity' => 40,
            'unit' => 'kg',
            'tags' => ['prawns', 'fresh', 'seafood'],
            'price' => 100.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Shrimp Cocktail',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/shrimp-cocktail.jpg',
            'summary' => 'Chilled shrimp cocktail, ready to serve.',
            'description' => 'Freshly cooked and chilled shrimp, perfect for a classic shrimp cocktail.',
            'quantity' => 25,
            'unit' => 'piece',
            'tags' => ['shrimp', 'cocktail', 'seafood'],
            'price' => 70.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Fresh Tiger Prawns',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/tiger-prawns.jpg',
            'summary' => 'Large tiger prawns, fresh and succulent.',
            'description' => 'These tiger prawns are ideal for grilling or adding to curries and stir-fries.',
            'quantity' => 35,
            'unit' => 'kg',
            'tags' => ['tiger prawns', 'fresh', 'seafood'],
            'price' => 130.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Garlic Butter Shrimp',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/garlic-butter-shrimp.jpg',
            'summary' => 'Shrimp sautéed in garlic butter.',
            'description' => 'Delicious shrimp sautéed in a rich garlic butter sauce, ready to serve.',
            'quantity' => 20,
            'unit' => 'piece',
            'tags' => ['shrimp', 'garlic butter', 'seafood'],
            'price' => 90.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Frozen Prawns',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/frozen-prawns.jpg',
            'summary' => 'Frozen prawns, ready to cook.',
            'description' => 'These prawns are cleaned, frozen, and ready to be used in your favorite dishes.',
            'quantity' => 60,
            'unit' => 'piece',
            'tags' => ['prawns', 'frozen', 'seafood'],
            'price' => 50.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Shrimp Skewers',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/shrimp-skewers.jpg',
            'summary' => 'Shrimp skewers, ready for grilling.',
            'description' => 'These shrimp skewers are perfect for grilling or roasting.',
            'quantity' => 45,
            'unit' => 'piece',
            'tags' => ['shrimp', 'skewers', 'seafood'],
            'price' => 85.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Spicy Prawn Curry',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/spicy-prawn-curry.jpg',
            'summary' => 'Prawns cooked in a spicy curry sauce.',
            'description' => 'Delicious prawns in a spicy, aromatic curry sauce, ready to heat and serve.',
            'quantity' => 30,
            'unit' => 'piece',
            'tags' => ['prawns', 'curry', 'seafood'],
            'price' => 95.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Lemon Garlic Prawns',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/lemon-garlic-prawns.jpg',
            'summary' => 'Prawns cooked in a lemon garlic sauce.',
            'description' => 'These prawns are sautéed in a tangy lemon garlic sauce, perfect as a main or appetizer.',
            'quantity' => 50,
            'unit' => 'piece',
            'tags' => ['prawns', 'lemon garlic', 'seafood'],
            'price' => 75.00,
        ],
        [
            'category_id' => 10,
            'name' => 'Breaded Shrimp',
            'picture' => 'assets/website/img/products/ocean-foods/shrimp-prawns/breaded-shrimp.jpg',
            'summary' => 'Crispy breaded shrimp.',
            'description' => 'Crispy and crunchy breaded shrimp, perfect for frying or baking.',
            'quantity' => 55,
            'unit' => 'piece',
            'tags' => ['shrimp', 'breaded', 'seafood'],
            'price' => 65.00,
        ],
        // End منتجات فئة 9,10: Butter & Eggs (Fresh Fish, Shrimp Prawns)

        // Start منتجات فئة 11,12: Butter & Eggs (Butter, Eggs)
        [
            'category_id' => 11,
            'name' => 'Salted Butter',
            'picture' => 'assets/website/img/products/butter-eggs/butter/salted-butter.jpg',
            'summary' => 'Rich and creamy salted butter.',
            'description' => 'Perfect for spreading on bread or cooking, this salted butter adds flavor to any dish.',
            'quantity' => 100,
            'unit' => 'kg', // Butter عادة يتم بيعها بالكيلو
            'tags' => ['butter', 'salted', 'dairy'],
            'price' => 40.00,
        ],
        [
            'category_id' => 11,
            'name' => 'Unsalted Butter',
            'picture' => 'assets/website/img/products/butter-eggs/butter/unsalted-butter.jpg',
            'summary' => 'Creamy unsalted butter.',
            'description' => 'Ideal for baking and cooking, this unsalted butter offers pure, creamy goodness.',
            'quantity' => 90,
            'unit' => 'kg', // Butter عادة يتم بيعها بالكيلو
            'tags' => ['butter', 'unsalted', 'dairy'],
            'price' => 42.00,
        ],
        [
            'category_id' => 11,
            'name' => 'Organic Butter',
            'picture' => 'assets/website/img/products/butter-eggs/butter/organic-butter.jpg',
            'summary' => 'Made from organic, grass-fed cows.',
            'description' => 'This organic butter is rich in flavor and made from the milk of grass-fed cows.',
            'quantity' => 80,
            'unit' => 'kg', // Butter عادة يتم بيعها بالكيلو
            'tags' => ['butter', 'organic', 'dairy'],
            'price' => 50.00,
        ],
        [
            'category_id' => 11,
            'name' => 'Clarified Butter (Ghee)',
            'picture' => 'assets/website/img/products/butter-eggs/butter/ghee.jpg',
            'summary' => 'Pure clarified butter, perfect for cooking.',
            'description' => 'This ghee is perfect for high-heat cooking, offering a rich and nutty flavor.',
            'quantity' => 70,
            'unit' => 'kg', // Ghee عادة يباع بالكيلو
            'tags' => ['butter', 'ghee', 'dairy'],
            'price' => 60.00,
        ],
        [
            'category_id' => 11,
            'name' => 'Whipped Butter',
            'picture' => 'assets/website/img/products/butter-eggs/butter/whipped-butter.jpg',
            'summary' => 'Light and airy whipped butter.',
            'description' => 'This whipped butter is easy to spread and perfect for breakfast items.',
            'quantity' => 60,
            'unit' => 'kg', // Butter مخفوق يباع بالكيلو
            'tags' => ['butter', 'whipped', 'dairy'],
            'price' => 45.00,
        ],
        [
            'category_id' => 12,
            'name' => 'Organic Eggs',
            'picture' => 'assets/website/img/products/butter-eggs/eggs/organic-eggs.jpg',
            'summary' => 'Fresh organic eggs from free-range chickens.',
            'description' => 'These organic eggs are high in nutrients and come from free-range chickens.',
            'quantity' => 150,
            'unit' => 'piece', // Eggs عادة تباع بالوحدة أو الدزينة
            'tags' => ['eggs', 'organic', 'dairy'],
            'price' => 30.00,
        ],
        [
            'category_id' => 12,
            'name' => 'Large Brown Eggs',
            'picture' => 'assets/website/img/products/butter-eggs/eggs/large-brown-eggs.jpg',
            'summary' => 'Fresh large brown eggs.',
            'description' => 'These large brown eggs are perfect for baking or breakfast dishes.',
            'quantity' => 140,
            'unit' => 'piece', // Eggs تباع بالوحدة
            'tags' => ['eggs', 'brown', 'dairy'],
            'price' => 28.00,
        ],
        [
            'category_id' => 12,
            'name' => 'Free-Range Eggs',
            'picture' => 'assets/website/img/products/butter-eggs/eggs/free-range-eggs.jpg',
            'summary' => 'Eggs from free-range chickens.',
            'description' => 'These free-range eggs are rich in flavor and nutrition.',
            'quantity' => 130,
            'unit' => 'piece', // Eggs تباع بالوحدة
            'tags' => ['eggs', 'free-range', 'dairy'],
            'price' => 32.00,
        ],
        [
            'category_id' => 12,
            'name' => 'Jumbo Eggs',
            'picture' => 'assets/website/img/products/butter-eggs/eggs/jumbo-eggs.jpg',
            'summary' => 'Extra-large jumbo eggs.',
            'description' => 'Perfect for large breakfasts or baking, these jumbo eggs are fresh and nutritious.',
            'quantity' => 120,
            'unit' => 'piece', // Eggs تباع بالوحدة
            'tags' => ['eggs', 'jumbo', 'dairy'],
            'price' => 34.00,
        ],
        [
            'category_id' => 12,
            'name' => 'Egg Whites',
            'picture' => 'assets/website/img/products/butter-eggs/eggs/egg-whites.jpg',
            'summary' => 'Pre-separated egg whites.',
            'description' => 'These egg whites are ideal for cooking and low-fat baking.',
            'quantity' => 110,
            'unit' => 'kg', // Egg whites عادة تباع بالكيلو
            'tags' => ['eggs', 'whites', 'dairy'],
            'price' => 25.00,
        ],
        // End منتجات فئة 11,12: Butter & Eggs (Butter, Eggs)

        // Start 13,14: Fastfood (Burgers, Pizza)
        [
            'category_id' => 13,
            'name' => 'Classic Beef Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/classic-beef-burger.jpg',
            'summary' => 'Juicy beef patty with lettuce, tomato, and cheese.',
            'description' => 'Our classic beef burger is made with a 100% beef patty, topped with fresh lettuce, tomato, and cheddar cheese.',
            'quantity' => 100,
            'unit' => 'piece', // البرغر عادة يباع بالقطعة
            'tags' => ['burger', 'beef', 'fastfood'],
            'price' => 10.00,
        ],
        [
            'category_id' => 13,
            'name' => 'Cheese Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/cheese-burger.jpg',
            'summary' => 'Classic burger with melted cheddar cheese.',
            'description' => 'A delicious cheese burger with a 100% beef patty and melted cheddar cheese.',
            'quantity' => 90,
            'unit' => 'piece',
            'tags' => ['burger', 'cheese', 'fastfood'],
            'price' => 12.00,
        ],
        [
            'category_id' => 13,
            'name' => 'Chicken Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/chicken-burger.jpg',
            'summary' => 'Grilled chicken patty with fresh toppings.',
            'description' => 'This chicken burger is grilled to perfection and topped with lettuce, tomato, and mayonnaise.',
            'quantity' => 85,
            'unit' => 'piece',
            'tags' => ['burger', 'chicken', 'fastfood'],
            'price' => 11.00,
        ],
        [
            'category_id' => 13,
            'name' => 'Veggie Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/veggie-burger.jpg',
            'summary' => 'A healthy option with a veggie patty.',
            'description' => 'Our veggie burger is made with a flavorful plant-based patty, topped with fresh lettuce, tomato, and onions.',
            'quantity' => 80,
            'unit' => 'piece',
            'tags' => ['burger', 'veggie', 'fastfood'],
            'price' => 9.00,
        ],
        [
            'category_id' => 13,
            'name' => 'BBQ Bacon Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/bbq-bacon-burger.jpg',
            'summary' => 'Beef patty with BBQ sauce and crispy bacon.',
            'description' => 'A savory burger with smoky BBQ sauce and crispy bacon, served on a toasted bun.',
            'quantity' => 75,
            'unit' => 'piece',
            'tags' => ['burger', 'bbq', 'bacon', 'fastfood'],
            'price' => 14.00,
        ],
        [
            'category_id' => 13,
            'name' => 'Spicy Beef Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/spicy-beef-burger.jpg',
            'summary' => 'Beef burger with spicy sauce.',
            'description' => 'A classic beef burger with a spicy kick, topped with jalapenos and spicy mayo.',
            'quantity' => 70,
            'unit' => 'piece',
            'tags' => ['burger', 'spicy', 'beef', 'fastfood'],
            'price' => 12.50,
        ],
        [
            'category_id' => 13,
            'name' => 'Mushroom Swiss Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/mushroom-swiss-burger.jpg',
            'summary' => 'Beef patty with mushrooms and Swiss cheese.',
            'description' => 'This burger is loaded with sauteed mushrooms and melted Swiss cheese on a juicy beef patty.',
            'quantity' => 65,
            'unit' => 'piece',
            'tags' => ['burger', 'mushroom', 'swiss', 'fastfood'],
            'price' => 13.00,
        ],
        [
            'category_id' => 13,
            'name' => 'Double Cheese Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/double-cheese-burger.jpg',
            'summary' => 'Double beef patties with extra cheese.',
            'description' => 'For the hungry ones, two beef patties with double the cheddar cheese.',
            'quantity' => 60,
            'unit' => 'piece',
            'tags' => ['burger', 'double', 'cheese', 'fastfood'],
            'price' => 16.00,
        ],
        [
            'category_id' => 13,
            'name' => 'Bacon Cheese Burger',
            'picture' => 'assets/website/img/products/fastfood/burgers/bacon-cheese-burger.jpg',
            'summary' => 'Classic burger with crispy bacon and cheddar cheese.',
            'description' => 'A juicy beef patty topped with crispy bacon and cheddar cheese on a toasted bun.',
            'quantity' => 55,
            'unit' => 'piece',
            'tags' => ['burger', 'bacon', 'cheese', 'fastfood'],
            'price' => 14.50,
        ],
        [
            'category_id' => 13,
            'name' => 'Sliders',
            'picture' => 'assets/website/img/products/fastfood/burgers/sliders.jpg',
            'summary' => 'Mini burgers perfect for sharing.',
            'description' => 'Three mini sliders with different flavors: beef, chicken, and veggie.',
            'quantity' => 50,
            'unit' => 'piece',
            'tags' => ['burger', 'sliders', 'fastfood'],
            'price' => 18.00,
        ],
        [
            'category_id' => 14,
            'name' => 'Margherita Pizza',
            'picture' => 'assets/website/img/products/fastfood/pizza/margherita-pizza.jpg',
            'summary' => 'Classic pizza with fresh mozzarella, tomatoes, and basil.',
            'description' => 'A simple and delicious pizza with fresh mozzarella, tomatoes, and basil, drizzled with olive oil.',
            'quantity' => 100,
            'unit' => 'piece', 
            'tags' => ['pizza', 'margherita', 'fastfood'],
            'price' => 15.00,
        ],
        [
            'category_id' => 14,
            'name' => 'Pepperoni Pizza',
            'picture' => 'assets/website/img/products/fastfood/pizza/pepperoni-pizza.jpg',
            'summary' => 'Pizza topped with pepperoni and mozzarella.',
            'description' => 'This classic pizza is loaded with pepperoni and melted mozzarella cheese.',
            'quantity' => 90,
            'unit' => 'piece',
            'tags' => ['pizza', 'pepperoni', 'fastfood'],
            'price' => 17.00,
        ],
        [
            'category_id' => 14,
            'name' => 'BBQ Chicken Pizza',
            'picture' => 'assets/website/img/products/fastfood/pizza/bbq-chicken-pizza.jpg',
            'summary' => 'Pizza topped with BBQ chicken, onions, and cheese.',
            'description' => 'A delicious pizza with BBQ chicken, red onions, and melted mozzarella cheese.',
            'quantity' => 85,
            'unit' => 'piece',
            'tags' => ['pizza', 'bbq', 'chicken', 'fastfood'],
            'price' => 18.00,
        ],
        [
            'category_id' => 14,
            'name' => 'Veggie Pizza',
            'picture' => 'assets/website/img/products/fastfood/pizza/veggie-pizza.jpg',
            'summary' => 'Pizza with a variety of fresh vegetables.',
            'description' => 'Our veggie pizza is loaded with bell peppers, onions, olives, and mushrooms.',
            'quantity' => 80,
            'unit' => 'piece',
            'tags' => ['pizza', 'veggie', 'fastfood'],
            'price' => 16.00,
        ],
        [
            'category_id' => 14,
            'name' => 'Meat Lover\'s Pizza',
            'picture' => 'assets/website/img/products/fastfood/pizza/meat-lovers-pizza.jpg',
            'summary' => 'Pizza with pepperoni, sausage, bacon, and ham.',
            'description' => 'A hearty pizza loaded with pepperoni, sausage, bacon, and ham.',
            'quantity' => 75,
            'unit' => 'piece',
            'tags' => ['pizza', 'meat', 'fastfood'],
            'price' => 19.00,
        ],
        // End منتجات فئة 13,14: Fastfood (Burgers, Pizza)
        
        // Start منتجات فئة 15: Fresh onions (Onion)
        [
            'category_id' => 15,
            'name' => 'Fresh Red Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/red-onions.jpg',
            'summary' => 'Crispy and flavorful fresh red onions.',
            'description' => 'These fresh red onions are perfect for salads, sandwiches, and cooking.',
            'quantity' => 100,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'red'],
            'price' => 1.20,
        ],
        [
            'category_id' => 15,
            'name' => 'Fresh Yellow Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/yellow-onions.jpg',
            'summary' => 'Versatile and aromatic fresh yellow onions.',
            'description' => 'Great for a variety of dishes, these yellow onions add depth of flavor.',
            'quantity' => 95,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'yellow'],
            'price' => 1.00,
        ],
        [
            'category_id' => 15,
            'name' => 'Fresh White Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/white-onions.jpg',
            'summary' => 'Mild and sweet fresh white onions.',
            'description' => 'These fresh white onions are perfect for salsas, salads, and garnishes.',
            'quantity' => 90,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'white'],
            'price' => 1.10,
        ],
        [
            'category_id' => 15,
            'name' => 'Fresh Green Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/green-onions.jpg',
            'summary' => 'Crisp and flavorful fresh green onions.',
            'description' => 'These fresh green onions add a mild flavor to salads and dishes.',
            'quantity' => 85,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'green'],
            'price' => 1.50,
        ],
        [
            'category_id' => 15,
            'name' => 'Organic Red Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/organic-red-onions.jpg',
            'summary' => 'Organic and flavorful fresh red onions.',
            'description' => 'Enjoy the rich flavor of organic red onions in your meals.',
            'quantity' => 80,
            'unit' => 'kg',
            'tags' => ['onions', 'organic', 'red'],
            'price' => 1.80,
        ],
        [
            'category_id' => 15,
            'name' => 'Organic Yellow Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/organic-yellow-onions.jpg',
            'summary' => 'Organic and versatile fresh yellow onions.',
            'description' => 'Add organic yellow onions for a depth of flavor in your dishes.',
            'quantity' => 75,
            'unit' => 'kg',
            'tags' => ['onions', 'organic', 'yellow'],
            'price' => 1.70,
        ],
        [
            'category_id' => 15,
            'name' => 'Fresh Sweet Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/sweet-onions.jpg',
            'summary' => 'Sweet and juicy fresh sweet onions.',
            'description' => 'Perfect for salads and caramelizing, these onions are a treat.',
            'quantity' => 70,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'sweet'],
            'price' => 1.60,
        ],
        [
            'category_id' => 15,
            'name' => 'Fresh Shallots',
            'picture' => 'assets/website/img/products/fresh-onion/onions/shallots.jpg',
            'summary' => 'Delicate and flavorful fresh shallots.',
            'description' => 'These shallots add a refined flavor to your cooking and salads.',
            'quantity' => 65,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'shallots'],
            'price' => 2.00,
        ],
        [
            'category_id' => 15,
            'name' => 'Fresh Pickling Onions',
            'picture' => 'assets/website/img/products/fresh-onion/onions/pickling-onions.jpg',
            'summary' => 'Crisp and small fresh pickling onions.',
            'description' => 'Great for pickling and adding to salads, these onions are a must-have.',
            'quantity' => 60,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'pickling'],
            'price' => 2.50,
        ],
        [
            'category_id' => 15,
            'name' => 'Fresh Onion Sets',
            'picture' => 'assets/website/img/products/fresh-onion/onions/onion-sets.jpg',
            'summary' => 'Fresh onion sets for planting.',
            'description' => 'Perfect for growing your own onions at home.',
            'quantity' => 55,
            'unit' => 'kg',
            'tags' => ['onions', 'fresh', 'sets'],
            'price' => 3.00,
        ],
        // End منتجات فئة 15: Fresh onions (Onion)
        
        // // Start منتجات فئة 16,17: Frozen Food (Frozen Pizza, Frozen Vegetables)
        // [
        //     'category_id' => 16,
        //     'name' => 'Four Cheese Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/four-cheese-pizza.jpg',
        //     'summary' => 'Frozen pizza topped with four different cheeses.',
        //     'description' => 'Enjoy the rich flavors of mozzarella, cheddar, parmesan, and blue cheese on this delicious frozen pizza.',
        //     'quantity' => 100,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'cheese'],
        //     'price' => 12.00,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Pepperoni Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/pepperoni-pizza.jpg',
        //     'summary' => 'Frozen pizza topped with pepperoni slices.',
        //     'description' => 'Classic pepperoni pizza, perfectly frozen for a quick and delicious meal.',
        //     'quantity' => 90,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'pepperoni'],
        //     'price' => 10.50,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'BBQ Chicken Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/bbq-chicken-pizza.jpg',
        //     'summary' => 'Frozen pizza with BBQ chicken, onions, and cheese.',
        //     'description' => 'Topped with grilled BBQ chicken and onions, this pizza is a favorite for all ages.',
        //     'quantity' => 85,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'bbq', 'chicken'],
        //     'price' => 11.00,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Margherita Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/margherita-pizza.jpg',
        //     'summary' => 'Frozen Margherita pizza with fresh basil and tomatoes.',
        //     'description' => 'A classic favorite with fresh tomatoes, mozzarella, and basil, frozen for convenience.',
        //     'quantity' => 80,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'margherita'],
        //     'price' => 11.50,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Veggie Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/veggie-pizza.jpg',
        //     'summary' => 'Frozen pizza loaded with fresh vegetables.',
        //     'description' => 'This pizza is packed with bell peppers, onions, mushrooms, and olives for a healthy option.',
        //     'quantity' => 75,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'veggie'],
        //     'price' => 10.00,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Meat Lovers Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/meat-lovers-pizza.jpg',
        //     'summary' => 'Frozen pizza loaded with pepperoni, sausage, and bacon.',
        //     'description' => 'A hearty pizza for meat lovers with a delicious combination of toppings.',
        //     'quantity' => 70,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'meat'],
        //     'price' => 13.00,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Hawaiian Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/hawaiian-pizza.jpg',
        //     'summary' => 'Frozen pizza with ham and pineapple.',
        //     'description' => 'A sweet and savory combination of ham and pineapple on a delicious pizza crust.',
        //     'quantity' => 65,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'hawaiian'],
        //     'price' => 11.50,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Buffalo Chicken Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/buffalo-chicken-pizza.jpg',
        //     'summary' => 'Spicy frozen pizza with buffalo chicken.',
        //     'description' => 'This pizza features spicy buffalo chicken topped with cheese, perfect for a kick.',
        //     'quantity' => 60,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'buffalo', 'chicken'],
        //     'price' => 12.00,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Spinach and Ricotta Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/spinach-ricotta-pizza.jpg',
        //     'summary' => 'Frozen pizza topped with spinach and ricotta cheese.',
        //     'description' => 'A delicious vegetarian option with spinach and creamy ricotta.',
        //     'quantity' => 55,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'spinach', 'ricotta'],
        //     'price' => 12.50,
        // ],
        // [
        //     'category_id' => 16,
        //     'name' => 'Seafood Frozen Pizza',
        //     'picture' => 'assets/website/img/products/frozen/seafood-pizza.jpg',
        //     'summary' => 'Frozen pizza topped with shrimp and crab.',
        //     'description' => 'A delicious seafood pizza featuring shrimp and crab meat.',
        //     'quantity' => 50,
        //     'unit' => 'piece',
        //     'tags' => ['frozen', 'pizza', 'seafood'],
        //     'price' => 14.00,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Mixed Frozen Vegetables',
        //     'picture' => 'assets/website/img/products/frozen/mixed-vegetables.jpg',
        //     'summary' => 'A mix of carrots, peas, and corn.',
        //     'description' => 'Convenient frozen mix of carrots, peas, and corn, perfect for side dishes.',
        //     'quantity' => 100,
        //     'unit' => 'bag', // كمية الخضروات عادة تباع في أكياس
        //     'tags' => ['frozen', 'vegetables', 'mixed'],
        //     'price' => 5.00,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Spinach',
        //     'picture' => 'assets/website/img/products/frozen/spinach.jpg',
        //     'summary' => 'Frozen spinach leaves.',
        //     'description' => 'Nutritious frozen spinach, perfect for cooking or adding to smoothies.',
        //     'quantity' => 90,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'spinach'],
        //     'price' => 4.50,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Broccoli',
        //     'picture' => 'assets/website/img/products/frozen/broccoli.jpg',
        //     'summary' => 'Frozen broccoli florets.',
        //     'description' => 'Fresh frozen broccoli florets, ideal for steaming or stir-frying.',
        //     'quantity' => 85,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'broccoli'],
        //     'price' => 5.50,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Cauliflower',
        //     'picture' => 'assets/website/img/products/frozen/cauliflower.jpg',
        //     'summary' => 'Frozen cauliflower florets.',
        //     'description' => 'Versatile frozen cauliflower florets, great for cooking or baking.',
        //     'quantity' => 80,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'cauliflower'],
        //     'price' => 5.00,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Green Beans',
        //     'picture' => 'assets/website/img/products/frozen/green-beans.jpg',
        //     'summary' => 'Frozen green beans, perfect for sides.',
        //     'description' => 'Fresh frozen green beans, great for salads and side dishes.',
        //     'quantity' => 75,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'green beans'],
        //     'price' => 4.00,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Corn',
        //     'picture' => 'assets/website/img/products/frozen/corn.jpg',
        //     'summary' => 'Frozen sweet corn kernels.',
        //     'description' => 'Sweet frozen corn kernels, perfect for soups and salads.',
        //     'quantity' => 70,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'corn'],
        //     'price' => 3.50,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Peas',
        //     'picture' => 'assets/website/img/products/frozen/peas.jpg',
        //     'summary' => 'Frozen green peas.',
        //     'description' => 'Sweet and tender frozen green peas, ideal for many dishes.',
        //     'quantity' => 65,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'peas'],
        //     'price' => 4.00,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Carrots',
        //     'picture' => 'assets/website/img/products/frozen/carrots.jpg',
        //     'summary' => 'Frozen sliced carrots.',
        //     'description' => 'Convenient frozen sliced carrots, perfect for stir-fries and soups.',
        //     'quantity' => 60,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'carrots'],
        //     'price' => 3.00,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Mixed Peppers',
        //     'picture' => 'assets/website/img/products/frozen/mixed-peppers.jpg',
        //     'summary' => 'Frozen mixed bell peppers.',
        //     'description' => 'A colorful mix of frozen bell peppers, great for fajitas and stir-fries.',
        //     'quantity' => 55,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'peppers'],
        //     'price' => 5.50,
        // ],
        // [
        //     'category_id' => 17,
        //     'name' => 'Frozen Sweet Potatoes',
        //     'picture' => 'assets/website/img/products/frozen/sweet-potatoes.jpg',
        //     'summary' => 'Frozen sweet potato chunks.',
        //     'description' => 'Nutritious frozen sweet potato chunks, perfect for roasting.',
        //     'quantity' => 50,
        //     'unit' => 'bag',
        //     'tags' => ['frozen', 'vegetables', 'sweet potatoes'],
        //     'price' => 6.00,
        // ],
        // // End منتجات فئة 16,17: Frozen Food (Frozen Pizza, Frozen Vegetables)

        // // Start منتجات فئة 18,19: Frozen Food (Papaya Chips, Crisps)
        // [
        //     'category_id' => 18,
        //     'name' => 'Original Papaya Chips',
        //     'picture' => 'assets/website/img/products/papaya/original-papaya-chips.jpg',
        //     'summary' => 'Crispy papaya chips, lightly salted.',
        //     'description' => 'Deliciously crispy papaya chips, perfect for snacking.',
        //     'quantity' => 100,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'chips'],
        //     'price' => 4.50,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Spicy Papaya Chips',
        //     'picture' => 'assets/website/img/products/papaya/spicy-papaya-chips.jpg',
        //     'summary' => 'Papaya chips with a spicy kick.',
        //     'description' => 'Enjoy a spicy twist on classic papaya chips for a flavorful snack.',
        //     'quantity' => 90,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'spicy'],
        //     'price' => 5.00,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Honey Glazed Papaya Chips',
        //     'picture' => 'assets/website/img/products/papaya/honey-glazed-papaya-chips.jpg',
        //     'summary' => 'Papaya chips coated with honey glaze.',
        //     'description' => 'A sweet treat made with natural honey for a delicious flavor.',
        //     'quantity' => 85,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'honey'],
        //     'price' => 5.50,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Salt & Vinegar Papaya Chips',
        //     'picture' => 'assets/website/img/products/papaya/salt-vinegar-papaya-chips.jpg',
        //     'summary' => 'Crispy papaya chips with salt and vinegar flavor.',
        //     'description' => 'A tangy and savory snack that tantalizes your taste buds.',
        //     'quantity' => 80,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'salt vinegar'],
        //     'price' => 5.00,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Cinnamon Papaya Chips',
        //     'picture' => 'assets/website/img/products/papaya/cinnamon-papaya-chips.jpg',
        //     'summary' => 'Papaya chips sprinkled with cinnamon.',
        //     'description' => 'A sweet and aromatic snack, perfect for cinnamon lovers.',
        //     'quantity' => 75,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'cinnamon'],
        //     'price' => 5.50,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Chocolate Covered Papaya Chips',
        //     'picture' => 'assets/website/img/products/papaya/chocolate-covered-papaya-chips.jpg',
        //     'summary' => 'Papaya chips dipped in rich chocolate.',
        //     'description' => 'Indulge in the perfect combination of sweet chocolate and crispy papaya.',
        //     'quantity' => 70,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'chocolate'],
        //     'price' => 6.00,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Papaya Coconut Chips',
        //     'picture' => 'assets/website/img/products/papaya/papaya-coconut-chips.jpg',
        //     'summary' => 'Papaya chips infused with coconut flavor.',
        //     'description' => 'A tropical delight combining the flavors of papaya and coconut.',
        //     'quantity' => 65,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'coconut'],
        //     'price' => 5.75,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Papaya and Nut Mix',
        //     'picture' => 'assets/website/img/products/papaya/papaya-nut-mix.jpg',
        //     'summary' => 'Papaya chips mixed with nuts.',
        //     'description' => 'A crunchy and healthy mix of papaya chips and assorted nuts.',
        //     'quantity' => 60,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'nuts'],
        //     'price' => 6.50,
        // ],
        // [
        //     'category_id' => 18,
        //     'name' => 'Tropical Fruit Mix',
        //     'picture' => 'assets/website/img/products/papaya/tropical-fruit-mix.jpg',
        //     'summary' => 'A mix of papaya and other tropical fruits.',
        //     'description' => 'A delicious mix of dried tropical fruits, including papaya.',
        //     'quantity' => 55,
        //     'unit' => 'bag',
        //     'tags' => ['papaya', 'snacks', 'fruit mix'],
        //     'price' => 7.00,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Classic Potato Crisps',
        //     'picture' => 'assets/website/img/products/crisps/classic-potato-crisps.jpg',
        //     'summary' => 'Crispy potato chips with a classic flavor.',
        //     'description' => 'Crunchy and salty potato crisps, perfect for snacking.',
        //     'quantity' => 100,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'potato'],
        //     'price' => 3.00,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'BBQ Flavored Crisps',
        //     'picture' => 'assets/website/img/products/crisps/bbq-crisps.jpg',
        //     'summary' => 'Crisps with a tangy BBQ flavor.',
        //     'description' => 'Enjoy the smoky flavor of BBQ in every crunchy bite.',
        //     'quantity' => 90,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'bbq'],
        //     'price' => 3.50,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Sour Cream and Onion Crisps',
        //     'picture' => 'assets/website/img/products/crisps/sour-cream-onion-crisps.jpg',
        //     'summary' => 'Crisps with sour cream and onion flavor.',
        //     'description' => 'A delicious blend of sour cream and onion in every crispy bite.',
        //     'quantity' => 85,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'sour cream', 'onion'],
        //     'price' => 3.50,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Salted Vinegar Crisps',
        //     'picture' => 'assets/website/img/products/crisps/salted-vinegar-crisps.jpg',
        //     'summary' => 'Crisps with a salty and vinegary taste.',
        //     'description' => 'Perfectly salted with a hint of vinegar for a tangy flavor.',
        //     'quantity' => 80,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'salted vinegar'],
        //     'price' => 3.50,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Cheese Crisps',
        //     'picture' => 'assets/website/img/products/crisps/cheese-crisps.jpg',
        //     'summary' => 'Crisps flavored with cheese.',
        //     'description' => 'Enjoy a cheesy snack that’s crispy and delicious.',
        //     'quantity' => 75,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'cheese'],
        //     'price' => 4.00,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Spicy Crisps',
        //     'picture' => 'assets/website/img/products/crisps/spicy-crisps.jpg',
        //     'summary' => 'Crisps with a spicy flavor.',
        //     'description' => 'Get ready for a kick with these spicy flavored crisps.',
        //     'quantity' => 70,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'spicy'],
        //     'price' => 4.00,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Honey Mustard Crisps',
        //     'picture' => 'assets/website/img/products/crisps/honey-mustard-crisps.jpg',
        //     'summary' => 'Crisps with a sweet and tangy honey mustard flavor.',
        //     'description' => 'A unique flavor combination for those who love sweet and tangy snacks.',
        //     'quantity' => 65,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'honey mustard'],
        //     'price' => 4.50,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Kettle Cooked Crisps',
        //     'picture' => 'assets/website/img/products/crisps/kettle-cooked-crisps.jpg',
        //     'summary' => 'Extra crispy kettle-cooked potato chips.',
        //     'description' => 'Thicker, crunchier chips made in small batches for maximum flavor.',
        //     'quantity' => 60,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'kettle cooked'],
        //     'price' => 4.00,
        // ],
        // [
        //     'category_id' => 19,
        //     'name' => 'Vegetable Crisps',
        //     'picture' => 'assets/website/img/products/crisps/vegetable-crisps.jpg',
        //     'summary' => 'Crisps made from a variety of vegetables.',
        //     'description' => 'A colorful mix of vegetable chips, healthier than regular crisps.',
        //     'quantity' => 55,
        //     'unit' => 'bag',
        //     'tags' => ['crisps', 'snacks', 'vegetables'],
        //     'price' => 4.50,
        // ],
        // // End منتجات فئة 18,19: Frozen Food (Papaya Chips, Crisps)
];

        foreach ($products as $item) {
            $product = Product::create([
                'name' => $item['name'],
                'picture' => $item['picture'],
                'summary' => $item['summary'],
                'description' => $item['description'],
                'quantity' => $item['quantity'],
                'price' => $item['price'],
                'unit' => $item['unit'],
                'category_id' => $item['category_id'],
                'is_active' => 1,
            ]);

            $product->attachTags($item['tags']);
        }
    }
}
