<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // منتجات فئة 1: Fresh Meat
[
    'category_id' => 1,
    'name' => 'Beef Steak',
    'picture' => 'assets/website/img/products/beef-steak.jpg',
    'summary' => 'Juicy beef steak, perfect for grilling.',
    'description' => 'Tender and flavorful steak, great for any occasion.',
    'quantity' => 50,
    'unit' => 'kg',
    'tags' => ['beef', 'steak', 'protein'],
    'price' => 120.00,
],
[
    'category_id' => 1,
    'name' => 'Ground Beef',
    'picture' => 'assets/website/img/products/ground-beef.jpg',
    'summary' => 'Fresh ground beef for various dishes.',
    'description' => 'Versatile ground beef, ideal for burgers and tacos.',
    'quantity' => 30,
    'unit' => 'kg',
    'tags' => ['beef', 'ground', 'protein'],
    'price' => 90.00,
],
[
    'category_id' => 1,
    'name' => 'Beef Ribs',
    'picture' => 'assets/website/img/products/beef-ribs.jpg',
    'summary' => 'Tender beef ribs for barbecue.',
    'description' => 'Delicious beef ribs, perfect for slow cooking.',
    'quantity' => 20,
    'unit' => 'kg',
    'tags' => ['beef', 'ribs', 'bbq'],
    'price' => 150.00,
],
[
    'category_id' => 1,
    'name' => 'Beef Jerky',
    'picture' => 'assets/website/img/products/beef-jerky.jpg',
    'summary' => 'Savory beef jerky for snacking.',
    'description' => 'High-protein snack, great for on-the-go.',
    'quantity' => 100,
    'unit' => 'kg',
    'tags' => ['snacks', 'beef', 'protein'],
    'price' => 250.00,
],
[
    'category_id' => 1,
    'name' => 'Beef Tenderloin',
    'picture' => 'assets/website/img/products/beef-tenderloin.jpg',
    'summary' => 'Premium beef tenderloin cut.',
    'description' => 'Top-quality tenderloin, perfect for fine dining.',
    'quantity' => 15,
    'unit' => 'kg',
    'tags' => ['beef', 'tenderloin', 'premium'],
    'price' => 200.00,
],

// منتجات فئة 2: Chicken
[
    'category_id' => 2,
    'name' => 'Grilled Chicken Breast',
    'picture' => 'assets/website/img/products/grilled-chicken-breast.jpg',
    'summary' => 'Lean grilled chicken breast, healthy and delicious.',
    'description' => 'Perfect for salads and healthy meals.',
    'quantity' => 40,
    'unit' => 'kg',
    'tags' => ['chicken', 'grilled', 'healthy'],
    'price' => 80.00,
],
[
    'category_id' => 2,
    'name' => 'Chicken Wings',
    'picture' => 'assets/website/img/products/chicken-wings.jpg',
    'summary' => 'Crispy chicken wings for snacking.',
    'description' => 'Spicy and crispy wings, perfect for parties.',
    'quantity' => 60,
    'unit' => 'kg',
    'tags' => ['chicken', 'wings', 'snacks'],
    'price' => 70.00,
],
[
    'category_id' => 2,
    'name' => 'Whole Chicken',
    'picture' => 'assets/website/img/products/whole-chicken.jpg',
    'summary' => 'Fresh whole chicken for roasting.',
    'description' => 'Perfectly fresh whole chicken for family dinners.',
    'quantity' => 30,
    'unit' => 'piece',
    'tags' => ['chicken', 'whole', 'roast'],
    'price' => 120.00,
],
[
    'category_id' => 2,
    'name' => 'Chicken Thighs',
    'picture' => 'assets/website/img/products/chicken-thighs.jpg',
    'summary' => 'Juicy chicken thighs for grilling.',
    'description' => 'Flavorful thighs, ideal for barbecues.',
    'quantity' => 25,
    'unit' => 'kg',
    'tags' => ['chicken', 'thighs', 'grilling'],
    'price' => 85.00,
],
[
    'category_id' => 2,
    'name' => 'Chicken Sausages',
    'picture' => 'assets/website/img/products/chicken-sausages.jpg',
    'summary' => 'Tasty chicken sausages for breakfast.',
    'description' => 'Delicious chicken sausages, great for brunch.',
    'quantity' => 50,
    'unit' => 'kg',
    'tags' => ['chicken', 'sausages', 'breakfast'],
    'price' => 95.00,
],

// منتجات فئة 3: Leafy Greens
[
    'category_id' => 3,
    'name' => 'Spinach',
    'picture' => 'assets/website/img/products/spinach.jpg',
    'summary' => 'Fresh spinach for salads and smoothies.',
    'description' => 'Nutritious spinach, rich in vitamins.',
    'quantity' => 100,
    'unit' => 'kg',
    'tags' => ['leafy', 'greens', 'healthy'],
    'price' => 30.00,
],
[
    'category_id' => 3,
    'name' => 'Kale',
    'picture' => 'assets/website/img/products/kale.jpg',
    'summary' => 'Superfood kale for healthy dishes.',
    'description' => 'Organic kale, perfect for salads and juices.',
    'quantity' => 80,
    'unit' => 'kg',
    'tags' => ['leafy', 'kale', 'superfood'],
    'price' => 40.00,
],
[
    'category_id' => 3,
    'name' => 'Romaine Lettuce',
    'picture' => 'assets/website/img/products/romaine-lettuce.jpg',
    'summary' => 'Crisp romaine lettuce for salads.',
    'description' => 'Fresh romaine, ideal for Caesar salads.',
    'quantity' => 120,
    'unit' => 'kg',
    'tags' => ['leafy', 'lettuce', 'fresh'],
    'price' => 25.00,
],
[
    'category_id' => 3,
    'name' => 'Swiss Chard',
    'picture' => 'assets/website/img/products/swiss-chard.jpg',
    'summary' => 'Colorful Swiss chard for sautéing.',
    'description' => 'Nutritious Swiss chard, great for cooking.',
    'quantity' => 50,
    'unit' => 'kg',
    'tags' => ['leafy', 'chard', 'healthy'],
    'price' => 45.00,
],
[
    'category_id' => 3,
    'name' => 'Arugula',
    'picture' => 'assets/website/img/products/arugula.jpg',
    'summary' => 'Peppery arugula for salads.',
    'description' => 'Fresh arugula, perfect for salads and sandwiches.',
    'quantity' => 90,
    'unit' => 'kg',
    'tags' => ['leafy', 'arugula', 'fresh'],
    'price' => 35.00,
],

[
    'category_id' => 4,
    'name' => 'Carrots',
    'picture' => 'assets/website/img/products/carrots.jpg',
    'summary' => 'Crunchy carrots, perfect for snacking.',
    'description' => 'Fresh carrots, great for salads and stews.',
    'quantity' => 150,
    'unit' => 'kg',
    'tags' => ['vegetables', 'carrots', 'fresh'],
    'price' => 1.50, 
],
[
    'category_id' => 4,
    'name' => 'Potatoes',
    'picture' => 'assets/website/img/products/potatoes.jpg',
    'summary' => 'Versatile potatoes for various dishes.',
    'description' => 'Fresh potatoes, perfect for mashing or frying.',
    'quantity' => 200,
    'unit' => 'kg',
    'tags' => ['vegetables', 'potatoes', 'fresh'],
    'price' => 1.20, 
],
[
    'category_id' => 4,
    'name' => 'Beets',
    'picture' => 'assets/website/img/products/beets.jpg',
    'summary' => 'Sweet beets for salads and roasting.',
    'description' => 'Nutritious beets, great for salads and sides.',
    'quantity' => 70,
    'unit' => 'kg',
    'tags' => ['vegetables', 'beets', 'healthy'],
    'price' => 2.00, 
],
[
    'category_id' => 4,
    'name' => 'Sweet Potatoes',
    'picture' => 'assets/website/img/products/sweet-potatoes.jpg',
    'summary' => 'Healthy sweet potatoes for baking.',
    'description' => 'Delicious sweet potatoes, great for roasting.',
    'quantity' => 80,
    'unit' => 'kg',
    'tags' => ['vegetables', 'sweet potatoes', 'healthy'],
    'price' => 1.80, 
],
[
    'category_id' => 4,
    'name' => 'Turnips',
    'picture' => 'assets/website/img/products/turnips.jpg',
    'summary' => 'Hearty turnips for soups and stews.',
    'description' => 'Nutritious turnips, perfect for cooking.',
    'quantity' => 60,
    'unit' => 'kg',
    'tags' => ['vegetables', 'turnips', 'fresh'],
    'price' => 1.30, 
],
[
    'category_id' => 6,
    'name' => 'Milk',
    'picture' => 'assets/website/img/products/milk.jpg',
    'summary' => 'Fresh whole milk.',
    'description' => 'Rich in calcium and vitamins, perfect for all ages.',
    'quantity' => 100,
    'unit' => 'liters',
    'tags' => ['dairy', 'milk', 'fresh'],
    'price' => 0.90, 
],
[
    'category_id' => 6,
    'name' => 'Yogurt',
    'picture' => 'assets/website/img/products/yogurt.jpg',
    'summary' => 'Creamy yogurt with live cultures.',
    'description' => 'Delicious yogurt, great for snacks or breakfast.',
    'quantity' => 80,
    'unit' => 'kg',
    'tags' => ['dairy', 'yogurt', 'healthy'],
    'price' => 1.50, 
],
[
    'category_id' => 6,
    'name' => 'Cheddar Cheese',
    'picture' => 'assets/website/img/products/cheddar-cheese.jpg',
    'summary' => 'Aged cheddar cheese.',
    'description' => 'Sharp and flavorful cheese, perfect for sandwiches.',
    'quantity' => 50,
    'unit' => 'kg',
    'tags' => ['dairy', 'cheese', 'cheddar'],
    'price' => 3.00, 
],
[
    'category_id' => 6,
    'name' => 'Butter',
    'picture' => 'assets/website/img/products/butter.jpg',
    'summary' => 'Rich and creamy butter.',
    'description' => 'Perfect for baking or spreading.',
    'quantity' => 75,
    'unit' => 'kg',
    'tags' => ['dairy', 'butter', 'cooking'],
    'price' => 2.50, 
],
[
    'category_id' => 6,
    'name' => 'Cream Cheese',
    'picture' => 'assets/website/img/products/cream-cheese.jpg',
    'summary' => 'Smooth cream cheese for spreading.',
    'description' => 'Ideal for bagels or cooking.',
    'quantity' => 60,
    'unit' => 'kg',
    'tags' => ['dairy', 'cream cheese', 'spreads'],
    'price' => 3.20, 
],
[
    'category_id' => 7,
    'name' => 'Chicken Breast',
    'picture' => 'assets/website/img/products/chicken-breast.jpg',
    'summary' => 'Lean chicken breast for healthy meals.',
    'description' => 'Versatile and delicious chicken breast.',
    'quantity' => 90,
    'unit' => 'kg',
    'tags' => ['meat', 'chicken', 'healthy'],
    'price' => 7.00, 
],
[
    'category_id' => 7,
    'name' => 'Beef Steak',
    'picture' => 'assets/website/img/products/beef-steak.jpg',
    'summary' => 'Tender beef steak for grilling.',
    'description' => 'Juicy steak, perfect for barbecues.',
    'quantity' => 45,
    'unit' => 'kg',
    'tags' => ['meat', 'beef', 'steak'],
    'price' => 12.00, 
],
[
    'category_id' => 7,
    'name' => 'Turkey',
    'picture' => 'assets/website/img/products/turkey.jpg',
    'summary' => 'Lean turkey meat for various dishes.',
    'description' => 'Great for sandwiches or roasting.',
    'quantity' => 50,
    'unit' => 'kg',
    'tags' => ['meat', 'turkey', 'lean'],
    'price' => 8.00, 
],
[
    'category_id' => 7,
    'name' => 'Lamb Chops',
    'picture' => 'assets/website/img/products/lamb-chops.jpg',
    'summary' => 'Tender lamb chops for grilling.',
    'description' => 'Delicious lamb chops, perfect for special occasions.',
    'quantity' => 30,
    'unit' => 'kg',
    'tags' => ['meat', 'lamb', 'chops'],
    'price' => 15.00, 
],


// منتجات فئة 8: Grains
[
    'category_id' => 8,
    'name' => 'Brown Rice',
    'picture' => 'assets/website/img/products/brown-rice.jpg',
    'summary' => 'Nutritious brown rice.',
    'description' => 'Healthy whole grain rice, great for sides.',
    'quantity' => 100,
    'unit' => 'kg',
    'tags' => ['grains', 'rice', 'healthy'],
    'price' => 15.00, 
],
[
    'category_id' => 8,
    'name' => 'Quinoa',
    'picture' => 'assets/website/img/products/quinoa.jpg',
    'summary' => 'Protein-rich quinoa.',
    'description' => 'Nutritious quinoa, perfect for salads and sides.',
    'quantity' => 75,
    'unit' => 'kg',
    'tags' => ['grains', 'quinoa', 'healthy'],
    'price' => 20.00, 
],
[
    'category_id' => 8,
    'name' => 'Whole Wheat Bread',
    'picture' => 'assets/website/img/products/whole-wheat-bread.jpg',
    'summary' => 'Fresh whole wheat bread.',
    'description' => 'Nutritious bread, great for sandwiches.',
    'quantity' => 80,
    'unit' => 'pieces',
    'tags' => ['grains', 'bread', 'whole wheat'],
    'price' => 10.00, 
],
[
    'category_id' => 8,
    'name' => 'Oats',
    'picture' => 'assets/website/img/products/oats.jpg',
    'summary' => 'Healthy rolled oats.',
    'description' => 'Great for breakfast or baking.',
    'quantity' => 90,
    'unit' => 'kg',
    'tags' => ['grains', 'oats', 'breakfast'],
    'price' => 12.00, 
],
[
    'category_id' => 8,
    'name' => 'Pasta',
    'picture' => 'assets/website/img/products/pasta.jpg',
    'summary' => 'Classic pasta for various dishes.',
    'description' => 'Versatile pasta, perfect for meals.',
    'quantity' => 100,
    'unit' => 'kg',
    'tags' => ['grains', 'pasta', 'versatile'],
    'price' => 18.00, 
],

// منتجات فئة 9: Snacks
[
    'category_id' => 9,
    'name' => 'Potato Chips',
    'picture' => 'assets/website/img/products/potato-chips.jpg',
    'summary' => 'Crispy potato chips.',
    'description' => 'Delicious chips, perfect for snacking.',
    'quantity' => 150,
    'unit' => 'kg',
    'tags' => ['snacks', 'chips', 'crispy'],
    'price' => 8.00, 
],
[
    'category_id' => 9,
    'name' => 'Granola Bars',
    'picture' => 'assets/website/img/products/granola-bars.jpg',
    'summary' => 'Healthy granola bars.',
    'description' => 'Nutritious bars, great for on-the-go snacking.',
    'quantity' => 80,
    'unit' => 'pieces',
    'tags' => ['snacks', 'granola', 'healthy'],
    'price' => 5.00, 
],
[
    'category_id' => 9,
    'name' => 'Chocolate',
    'picture' => 'assets/website/img/products/chocolate.jpg',
    'summary' => 'Rich chocolate bars.',
    'description' => 'Delicious chocolate, perfect for a sweet treat.',
    'quantity' => 100,
    'unit' => 'kg',
    'tags' => ['snacks', 'chocolate', 'sweet'],
    'price' => 25.00, 
],
[
    'category_id' => 9,
    'name' => 'Trail Mix',
    'picture' => 'assets/website/img/products/trail-mix.jpg',
    'summary' => 'Nutty and fruity trail mix.',
    'description' => 'Great for hiking or snacking.',
    'quantity' => 60,
    'unit' => 'kg',
    'tags' => ['snacks', 'trail mix', 'healthy'],
    'price' => 15.00, 
],
[
    'category_id' => 9,
    'name' => 'Popcorn',
    'picture' => 'assets/website/img/products/popcorn.jpg',
    'summary' => 'Light and airy popcorn.',
    'description' => 'Perfect for movie nights.',
    'quantity' => 90,
    'unit' => 'kg',
    'tags' => ['snacks', 'popcorn', 'light'],
    'price' => 7.00, 
],

// منتجات فئة 10: Beverages
[
    'category_id' => 10,
    'name' => 'Orange Juice',
    'picture' => 'assets/website/img/products/orange-juice.jpg',
    'summary' => 'Freshly squeezed orange juice.',
    'description' => 'Rich in vitamin C, perfect for breakfast.',
    'quantity' => 100,
    'unit' => 'liters',
    'tags' => ['beverages', 'juice', 'orange'],
    'price' => 12.00, 
],
[
    'category_id' => 10,
    'name' => 'Green Tea',
    'picture' => 'assets/website/img/products/green-tea.jpg',
    'summary' => 'Healthy green tea.',
    'description' => 'Rich in antioxidants, great for relaxation.',
    'quantity' => 80,
    'unit' => 'kg',
    'tags' => ['beverages', 'tea', 'green'],
    'price' => 10.00, 
],
[
    'category_id' => 10,
    'name' => 'Coffee',
    'picture' => 'assets/website/img/products/coffee.jpg',
    'summary' => 'Rich coffee blend.',
    'description' => 'Perfect for a morning boost.',
    'quantity' => 50,
    'unit' => 'kg',
    'tags' => ['beverages', 'coffee', 'caffeine'],
    'price' => 20.00, 
],
[
    'category_id' => 10,
    'name' => 'Sparkling Water',
    'picture' => 'assets/website/img/products/sparkling-water.jpg',
    'summary' => 'Refreshing sparkling water.',
    'description' => 'Great alternative to soda.',
    'quantity' => 90,
    'unit' => 'liters',
    'tags' => ['beverages', 'water', 'sparkling'],
    'price' => 5.00, 
],
[
    'category_id' => 10,
    'name' => 'Lemonade',
    'picture' => 'assets/website/img/products/lemonade.jpg',
    'summary' => 'Refreshing lemonade.',
    'description' => 'Sweet and tangy, perfect for summer.',
    'quantity' => 60,
    'unit' => 'liters',
    'tags' => ['beverages', 'lemonade', 'refreshing'],
    'price' => 8.00, 
],


           // منتجات فئة 11: Seafood
[
    'category_id' => 11,
    'name' => 'Salmon Fillet',
    'picture' => 'assets/website/img/products/salmon-fillet.jpg',
    'summary' => 'Fresh salmon fillet.',
    'description' => 'Rich in omega-3 fatty acids, perfect for grilling.',
    'quantity' => 70,
    'unit' => 'kg', 
    'tags' => ['seafood', 'fish', 'salmon'],
    'price' => 25.00, 
],
[
    'category_id' => 11,
    'name' => 'Shrimp',
    'picture' => 'assets/website/img/products/shrimp.jpg',
    'summary' => 'Fresh shrimp for various dishes.',
    'description' => 'Delicious shrimp, great for pasta or salads.',
    'quantity' => 80,
    'unit' => 'kg', 
    'tags' => ['seafood', 'shrimp', 'fresh'],
    'price' => 30.00, 
],
[
    'category_id' => 11,
    'name' => 'Tuna',
    'picture' => 'assets/website/img/products/tuna.jpg',
    'summary' => 'Canned tuna for easy meals.',
    'description' => 'Versatile and convenient for sandwiches or salads.',
    'quantity' => 100,
    'unit' => 'kg', 
    'tags' => ['seafood', 'tuna', 'canned'],
    'price' => 15.00, 
],
[
    'category_id' => 11,
    'name' => 'Crab',
    'picture' => 'assets/website/img/products/crab.jpg',
    'summary' => 'Fresh crab meat.',
    'description' => 'Delicious crab, perfect for seafood dishes.',
    'quantity' => 50,
    'unit' => 'kg', 
    'tags' => ['seafood', 'crab', 'fresh'],
    'price' => 40.00, 
],
[
    'category_id' => 11,
    'name' => 'Mussels',
    'picture' => 'assets/website/img/products/mussels.jpg',
    'summary' => 'Fresh mussels for cooking.',
    'description' => 'Great for steaming or in pasta dishes.',
    'quantity' => 40,
    'unit' => 'kg', 
    'tags' => ['seafood', 'mussels', 'fresh'],
    'price' => 20.00, 
],

// منتجات فئة 12: Fruits
[
    'category_id' => 12,
    'name' => 'Apples',
    'picture' => 'assets/website/img/products/apples.jpg',
    'summary' => 'Fresh apples.',
    'description' => 'Crisp and juicy apples, great for snacking.',
    'quantity' => 100,
    'unit' => 'pieces', 
    'tags' => ['fruits', 'apples', 'fresh'],
    'price' => 1.00, 
],
[
    'category_id' => 12,
    'name' => 'Bananas',
    'picture' => 'assets/website/img/products/bananas.jpg',
    'summary' => 'Ripe bananas.',
    'description' => 'Sweet and convenient for on-the-go snacks.',
    'quantity' => 80,
    'unit' => 'pieces', 
    'tags' => ['fruits', 'bananas', 'healthy'],
    'price' => 0.50, 
],
[
    'category_id' => 12,
    'name' => 'Oranges',
    'picture' => 'assets/website/img/products/oranges.jpg',
    'summary' => 'Fresh oranges.',
    'description' => 'Sweet and tangy oranges, perfect for juicing.',
    'quantity' => 90,
    'unit' => 'pieces', 
    'tags' => ['fruits', 'oranges', 'fresh'],
    'price' => 0.80, 
],
[
    'category_id' => 12,
    'name' => 'Strawberries',
    'picture' => 'assets/website/img/products/strawberries.jpg',
    'summary' => 'Fresh strawberries.',
    'description' => 'Sweet and juicy strawberries for desserts.',
    'quantity' => 60,
    'unit' => 'pieces', 
    'tags' => ['fruits', 'strawberries', 'fresh'],
    'price' => 2.00, 
],
[
    'category_id' => 12,
    'name' => 'Grapes',
    'picture' => 'assets/website/img/products/grapes.jpg',
    'summary' => 'Sweet grapes.',
    'description' => 'Great for snacking or in fruit salads.',
    'quantity' => 50,
    'unit' => 'kg', 
    'tags' => ['fruits', 'grapes', 'fresh'],
    'price' => 3.00, 
],

// منتجات فئة 15: Baked Goods
[
    'category_id' => 15,
    'name' => 'Bread',
    'picture' => 'assets/website/img/products/bread.jpg',
    'summary' => 'Freshly baked bread.',
    'description' => 'Perfect for sandwiches or toasts.',
    'quantity' => 100,
    'unit' => 'kg', 
    'tags' => ['baked goods', 'bread', 'fresh'],
    'price' => 1.50, 
],
[
    'category_id' => 15,
    'name' => 'Croissant',
    'picture' => 'assets/website/img/products/croissant.jpg',
    'summary' => 'Flaky and buttery croissant.',
    'description' => 'Perfect for breakfast or snacks.',
    'quantity' => 80,
    'unit' => 'pieces', 
    'tags' => ['baked goods', 'croissant', 'breakfast'],
    'price' => 1.20, 
],
[
    'category_id' => 15,
    'name' => 'Cookies',
    'picture' => 'assets/website/img/products/cookies.jpg',
    'summary' => 'Delicious cookies.',
    'description' => 'Perfect for snacks or desserts.',
    'quantity' => 90,
    'unit' => 'pieces', 
    'tags' => ['baked goods', 'cookies', 'snack'],
    'price' => 0.80, 
],
[
    'category_id' => 15,
    'name' => 'Muffins',
    'picture' => 'assets/website/img/products/muffins.jpg',
    'summary' => 'Delicious muffins.',
    'description' => 'Perfect for breakfast or snacks.',
    'quantity' => 60,
    'unit' => 'pieces', 
    'tags' => ['baked goods', 'muffins', 'breakfast'],
    'price' => 1.50, 
],
[
    'category_id' => 15,
    'name' => 'Brownies',
    'picture' => 'assets/website/img/products/brownies.jpg',
    'summary' => 'Fudgy brownies.',
    'description' => 'Perfect for dessert.',
    'quantity' => 50,
    'unit' => 'kg',
    'tags' => ['baked goods', 'brownies', 'dessert'],
    'price' => 3.50, 
],
        ];

        foreach ($products as $item) {
            $product = Product::create([
                'name' => $item['name'],
                'picture' => $item['picture'],
                'summary' => $item['summary'],
                'description' => $item['description'],
                'quantity' => $item['quantity'],
                'price' => $item['price'],
                'unit' => $item['unit'],
                'category_id' => $item['category_id'],
                'is_active' => 1,
            ]);

            $product->attachTags($item['tags']);
        }
    }
}
